import os
import json
import logging
from typing import Optional, List, Dict, Any
from app.core.config import settings

logger = logging.getLogger("ai_service.gemini")

class GeminiService:
    _configured: bool = False
    _model = None

    def __init__(self):
        self._init_gemini()

    def _init_gemini(self) -> None:
        """Initialize Google Generative AI client if API key is provided."""
        api_key = settings.GEMINI_API_KEY or os.environ.get("GEMINI_API_KEY", "")
        if api_key and api_key != "your_gemini_api_key_here":
            try:
                import google.generativeai as genai
                genai.configure(api_key=api_key)
                self._model = genai.GenerativeModel(settings.GEMINI_MODEL)
                self._configured = True
                logger.info(f"Google Gemini configured with model: {settings.GEMINI_MODEL}")
            except Exception as e:
                logger.error(f"Failed to initialize Google Gemini client: {e}")
                self._configured = False
        else:
            logger.warning("GEMINI_API_KEY not configured or using default placeholder.")
            self._configured = False

    def is_configured(self) -> bool:
        # Re-check in case key was updated in environment dynamically
        if not self._configured:
            self._init_gemini()
        return self._configured

    async def generate_grounded_answer(
        self,
        question: str,
        context: str,
        conversation_history: Optional[List[Dict[str, str]]] = None
    ) -> str:
        """
        Generate grounded response from Gemini based strictly on retrieved ProjectVault context.
        """
        if not self.is_configured():
            return (
                "Gemini API key is not configured on the AI Service. "
                "Retrieved ProjectVault projects are listed below."
            )

        system_instruction = (
            "You are the official ProjectVault AI Research Assistant. Your role is to assist students, faculty, "
            "and visitors in exploring the university's academic project repository.\n\n"
            "STRICT RULES:\n"
            "1. Answer the question PRIMARILY using the provided ProjectVault Context.\n"
            "2. Do NOT invent or hallucinate projects, authors, or technologies that do not exist in the context.\n"
            "3. When referencing projects, clearly cite their exact Title and Project ID.\n"
            "4. If the provided context does not contain enough information to answer the question, clearly state: "
            "'Based on the current ProjectVault repository, there are no matching projects or sufficient data to answer this question.'\n"
            "5. Keep responses concise, well-structured, professional, and academic.\n"
        )

        prompt = f"""{system_instruction}

--- PROJECTVAULT RETRIEVED CONTEXT ---
{context}
-------------------------------------

User Question: {question}

Please provide a grounded, helpful answer based exclusively on the retrieved ProjectVault project context above:"""

        try:
            response = self._model.generate_content(prompt)
            if response and response.text:
                return response.text.strip()
            return "No response generated by Gemini."
        except Exception as e:
            logger.error(f"Gemini API error during grounded answer generation: {e}")
            return f"An error occurred while communicating with Gemini LLM: {str(e)}"

    async def analyze_project(
        self,
        title: str,
        abstract: str,
        document_text: Optional[str] = None
    ) -> Dict[str, Any]:
        """
        Extract structured project metadata (summary, domain, tech stack, keywords, problem statement).
        """
        if not self.is_configured():
            logger.info("Gemini not configured; using heuristic analysis fallback.")
            return self._heuristic_analysis(title, abstract, document_text)

        content_sample = f"Title: {title}\nAbstract: {abstract}"
        if document_text:
            # Truncate to first 4000 characters to stay within fast token boundaries
            content_sample += f"\nDocument Excerpt:\n{document_text[:4000]}"

        prompt = f"""You are an expert academic project reviewer. Analyze the following university project submission and extract structured technical metadata in valid JSON format.

Project Content:
{content_sample}

You MUST return ONLY a valid JSON object with the following exact keys:
{{
  "summary": "Concise 2-3 sentence academic summary of the project goals and methodology.",
  "domain": "Primary academic/industry domain (e.g., Computer Vision, Distributed Systems, Internet of Things, Artificial Intelligence, Blockchain, Cybersecurity, Web Engineering, Healthcare Informatics, Data Science).",
  "sub_domains": ["Subdomain 1", "Subdomain 2"],
  "tech_stack": ["Identified technology/library/framework 1", "Technology 2"],
  "extracted_keywords": ["Keyword 1", "Keyword 2", "Keyword 3", "Keyword 4"],
  "problem_statement": "Clear 1-2 sentence definition of the core problem this project solves."
}}

Do not include markdown code block formatting (```json), return purely the JSON string."""

        try:
            response = self._model.generate_content(prompt)
            text = response.text.strip()
            # Clean possible markdown formatting
            if text.startswith("```json"):
                text = text[7:]
            if text.startswith("```"):
                text = text[3:]
            if text.endswith("```"):
                text = text[:-3]
            text = text.strip()

            parsed = json.loads(text)
            return {
                "summary": parsed.get("summary", abstract[:200]),
                "domain": parsed.get("domain", "Computer Science"),
                "sub_domains": parsed.get("sub_domains", []),
                "tech_stack": parsed.get("tech_stack", []),
                "extracted_keywords": parsed.get("extracted_keywords", []),
                "problem_statement": parsed.get("problem_statement", abstract[:150]),
                "ai_status": "COMPLETED"
            }
        except Exception as e:
            logger.warning(f"Gemini project analysis failed or returned invalid JSON: {e}. Falling back to heuristic extractor.")
            return self._heuristic_analysis(title, abstract, document_text)

    def _heuristic_analysis(
        self,
        title: str,
        abstract: str,
        document_text: Optional[str] = None
    ) -> Dict[str, Any]:
        """Local rule-based heuristic extraction fallback when LLM is unavailable."""
        combined_text = f"{title} {abstract} {document_text or ''}".lower()
        
        # Domain detection rules
        domain = "Computer Science"
        sub_domains = []
        if any(k in combined_text for k in ["deep learning", "cnn", "neural network", "computer vision", "yolo", "resnet", "leaf disease", "image classification"]):
            domain = "Computer Vision & Deep Learning"
            sub_domains.append("Convolutional Neural Networks")
        elif any(k in combined_text for k in ["iot", "sensor", "arduino", "esp32", "mqtt", "raspberry pi", "smart parking"]):
            domain = "Internet of Things (IoT)"
            sub_domains.append("Embedded Systems")
        elif any(k in combined_text for k in ["blockchain", "smart contract", "ethereum", "solidity", "cryptocurrency", "consortium"]):
            domain = "Blockchain & Distributed Ledgers"
            sub_domains.append("Decentralized Systems")
        elif any(k in combined_text for k in ["quantum", "cryptography", "lattice", "post-quantum"]):
            domain = "Cybersecurity & Cryptography"
            sub_domains.append("Post-Quantum Cryptography")
        elif any(k in combined_text for k in ["nlp", "transformer", "bert", "gpt", "rag", "llm", "language model"]):
            domain = "Natural Language Processing"
            sub_domains.append("Generative AI")

        # Tech stack dictionary matching
        known_techs = [
            "Python", "TensorFlow", "PyTorch", "OpenCV", "CNN", "ResNet50", "Deep Learning",
            "React", "Spring Boot", "FastAPI", "PostgreSQL", "pgvector", 
            "Docker", "MQTT", "Ethereum", "Solidity", "Node.js", "Java", "TypeScript", "Redis", 
            "Kubernetes", "AWS", "Scikit-Learn", "Next.js", "Lattice Cryptography"
        ]
        detected_tech = [t for t in known_techs if t.lower() in combined_text]
        if "deep learning" in combined_text or "cnn" in combined_text or "resnet" in combined_text:
            if "Python" not in detected_tech:
                detected_tech.append("Python")
            if "TensorFlow" not in detected_tech and "PyTorch" not in detected_tech:
                detected_tech.append("TensorFlow")
        if not detected_tech:
            detected_tech = ["Python", "FastAPI"]

        # Simple keyword extraction
        words = [w.strip(".,;:()[]{}'\"") for w in f"{title} {abstract}".split() if len(w) > 4]
        extracted_keywords = list(dict.fromkeys(words))[:6]

        return {
            "summary": abstract if len(abstract) <= 300 else abstract[:297] + "...",
            "domain": domain,
            "sub_domains": sub_domains,
            "tech_stack": detected_tech,
            "extracted_keywords": extracted_keywords,
            "problem_statement": f"Addressing challenges in {domain.lower()} by developing {title.lower()}.",
            "ai_status": "HEURISTIC_FALLBACK"
        }

gemini_service = GeminiService()
