ALTER TABLE projects ADD COLUMN IF NOT EXISTS plagiarism_score DOUBLE PRECISION;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS duplication_score DOUBLE PRECISION;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS plagiarism_report TEXT;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS plagiarism_status VARCHAR(50) DEFAULT 'NOT_SCANNED';
